name: 🚀 Deploy Project to Production
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: 7.4

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    # - name: Copy .env from .env.example
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # - name: Jorge's bash
    #   run: bash
    #     echo "" > .env.li
    #     while read line;
    #     do
    #       new_line=$line
    #       key=(${line//"="/ })
    #       param=${key[1]}

    #       value=(${param//"."/ })
    #       validator=${value[0]}
    #       name=${value[1]}
    #       if [[ $validator = "GHS" ]]; then
    #         valuee = ${{ secrets.${name} }}
    #         new_line="${key}=${valuee}"
    #       fi
    #       echo $new_line >> .env.li
    #     done < .env.example

    - name: Create .env File
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_HOSTNAME: localhost
        envkey_DB_USERNAME: ${{ secrets.DB_USERNAME}}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_DATABASE: coopele1_erpdemo
        some_other_variable: foobar
        directory: ./
        file_name: .env
        fail_on_empty: false

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-plugins --prefer-dist --no-progress

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /erpdemo/

